# Generated by Django 3.2.9 on 2024-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TollData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_interchange", models.CharField(max_length=100)),
                (
                    "exit_interchange",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("number_plate", models.CharField(max_length=20)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
